# Generated by Django 4.1.5 on 2023-01-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_label', models.CharField(help_text="Enter note's label", max_length=50, verbose_name='My note')),
                ('note_text', models.CharField(blank=True, help_text="Enter note's text", max_length=300, null=True, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='NoteDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_label', models.CharField(max_length=20, verbose_name='Enter datafile label')),
                ('db_date', models.DateField(default='2023-01-22', verbose_name='Enter date in format YYYY-MM-DD')),
                ('db_path', models.FileField(upload_to='password_files', verbose_name='".json" file')),
            ],
        ),
    ]
