# Generated by Django 4.1.5 on 2023-01-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedb',
            name='db_date',
            field=models.DateField(default='2023-01-23', verbose_name='Enter date in format YYYY-MM-DD'),
        ),
    ]
