# Generated by Django 4.1.5 on 2023-01-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebNotes', '0002_alter_notedb_db_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notedb',
            name='db_date',
            field=models.DateField(default='2023-01-27', verbose_name='Enter date in format YYYY-MM-DD'),
        ),
    ]
