# Generated by Django 4.1.5 on 2023-02-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebNotes', '0004_alter_note_note_label_alter_note_note_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_label', models.CharField(help_text="Enter note's label", max_length=100, verbose_name="Note's label")),
                ('note_text', models.TextField(default='', help_text="Enter note's text", verbose_name="Note's text")),
            ],
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteDB',
        ),
    ]
