# Generated by Django 4.1.7 on 2023-03-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebNotes', '0006_remove_textnote_note_label_textnote_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textnote',
            name='note_title',
            field=models.CharField(default='', help_text="Enter note's label", max_length=50, verbose_name="Note's title"),
        ),
    ]
